# Ubuntu 20.04
dist: focal

#services:
#  - xvfb
language: python
cache: pip
addons:
  postgresql: "13"
services:
  - postgresql
env:
  global:
    - USE_DOCKER=no
    - DJANGO_SETTINGS_MODULE=config.settings.test
python:
  - 3.8
install:
  - pushd /tmp
  - git clone https://github.com/ContactEngineering/topobank.git
  - cd topobank
  - git checkout 23_tweaks2
  - pip install -q -r requirements/local.txt
  - pip install -e .[dev]
  - USE_DOCKER=no python manage.py collectstatic
  - popd
  - pip install -e .[dev]
script:
  - pytest -v
notifications:
  email:
    - roettger@tf.uni-freiburg.de
    # - lars.pastewka@imtek.uni-freiburg.de
