# Ubuntu 20.04
dist: focal

#services:
#  - xvfb
language: python
cache: pip
addons:
  postgresql: "13"
services:
  - postgresql
env:
  global:
    - USE_DOCKER=no
    - DJANGO_SETTINGS_MODULE=config.settings.test
python:
  - 3.8
install:
  - sudo apt-get install libfftw3-dev libopenblas-dev
  - pushd /tmp
  - git clone git@github.com:ContactEngineering/TopoBank.git
  - cd topobank
  - git checkout 22_analysis_plugins
  - pip install -q -r requirements/local.txt --no-binary numpy
  - pip install -e .[dev]
  - python manage.py collectstatic
  - popd
  - pip install -e .[dev] --no-binary numpy
script:
  - pytest -v
notifications:
  email:
    - roettger@tf.uni-freiburg.de
    # - lars.pastewka@imtek.uni-freiburg.de
